project: 
  type: website
  output-dir: docs
  
format:
  html:
    theme: Lumen
    css: styles.css
  
website: 
  title: "BIOL 607/617 Assignments"
  navbar: 
    tools:
      - icon: github
        href: https://github.com/DantonyL
    left: 
      - href: index.qmd
      - text: "Home"
      - HW1_Intro_to_R.qmd
      - HW2_ggplot.qmd
      - HW3_Tidy_Data.qmd
      - HW4_Sampling.qmd
      - HW5_Linear_Regression.qmd
      - HW6_Complex_Linear_Model.qmd
      
  