project: 
  type: website
  output-dir: docs
  
website: 
  title: "BIOL 607/617 Assignments"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - HW1_Intro_to_R.qmd
      - HW2_ggplot.qmd
      
  