<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>HW1 Intro to R – BIOL 607/617 Assignments</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">BIOL 607/617 Assignments</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./HW1_Intro_to_R.html" aria-current="page"> 
<span class="menu-text">HW1 Intro to R</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./HW2_ggplot.html"> 
<span class="menu-text">HW2 ggplot</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HW1 Intro to R</h1>
<p class="subtitle lead">BIOL 607</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="earthquakes-off-fiji" class="level1">
<h1>Earthquakes off Fiji</h1>
<section id="str-summary" class="level3">
<h3 class="anchored" data-anchor-id="str-summary">1 - str() &amp; summary()</h3>
<p>With the <strong>str()</strong> function you are able to view the amount of observations in data frame, view the amount fo variables/row, and view the class of certain objects. <strong>summary()</strong> can be used to find different aggregate functions of each variable given in data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(quakes)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(quakes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1000 obs. of  5 variables:
 $ lat     : num  -20.4 -20.6 -26 -18 -20.4 ...
 $ long    : num  182 181 184 182 182 ...
 $ depth   : int  562 650 42 626 649 195 82 194 211 622 ...
 $ mag     : num  4.8 4.2 5.4 4.1 4 4 4.8 4.4 4.7 4.3 ...
 $ stations: int  41 15 43 19 11 12 43 15 35 19 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(quakes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      lat              long           depth            mag      
 Min.   :-38.59   Min.   :165.7   Min.   : 40.0   Min.   :4.00  
 1st Qu.:-23.47   1st Qu.:179.6   1st Qu.: 99.0   1st Qu.:4.30  
 Median :-20.30   Median :181.4   Median :247.0   Median :4.60  
 Mean   :-20.64   Mean   :179.5   Mean   :311.4   Mean   :4.62  
 3rd Qu.:-17.64   3rd Qu.:183.2   3rd Qu.:543.0   3rd Qu.:4.90  
 Max.   :-10.72   Max.   :188.1   Max.   :680.0   Max.   :6.40  
    stations     
 Min.   : 10.00  
 1st Qu.: 18.00  
 Median : 27.00  
 Mean   : 33.42  
 3rd Qu.: 42.00  
 Max.   :132.00  </code></pre>
</div>
</div>
</section>
<section id="showing-entirety-of-column" class="level3">
<h3 class="anchored" data-anchor-id="showing-entirety-of-column">2 - Showing Entirety of Column</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>quakes<span class="sc">$</span>long</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   [1] 181.62 181.03 184.10 181.66 181.96 184.31 166.10 181.93 181.74 179.59
  [11] 180.69 167.00 182.11 181.66 169.92 184.95 165.96 181.50 179.78 180.31
  [21] 181.16 166.32 180.16 182.00 180.28 181.49 167.51 180.79 181.47 182.37
  [31] 179.24 166.74 185.05 180.80 186.00 179.33 169.23 181.28 181.40 169.33
  [41] 176.78 186.10 179.82 186.04 169.41 182.30 181.70 166.32 180.08 185.25
  [51] 182.35 184.42 173.20 180.67 182.16 182.13 181.00 180.60 181.35 179.20
  [61] 181.55 182.40 172.38 166.22 181.41 184.93 181.60 179.62 181.86 187.81
  [71] 185.80 184.35 166.20 179.99 181.23 180.04 184.70 167.06 181.71 181.11
  [81] 180.21 180.99 182.38 183.40 181.70 184.31 170.50 179.96 186.30 186.44
  [91] 167.53 167.06 182.02 169.71 185.26 182.40 181.11 183.41 166.54 179.92
 [101] 185.61 178.41 180.39 181.60 180.69 183.50 180.60 169.49 185.90 177.81
 [111] 185.23 182.31 182.45 178.30 178.35 178.31 172.23 172.29 167.40 169.48
 [121] 166.97 178.90 180.40 182.43 180.60 167.89 183.84 178.57 181.70 183.51
 [131] 185.43 181.22 168.98 180.30 180.82 168.02 187.32 182.80 182.60 184.16
 [141] 169.46 181.40 167.10 181.43 173.50 184.40 185.17 173.49 180.17 181.50
 [151] 184.50 167.62 182.56 165.80 167.68 181.32 166.07 180.00 169.84 166.24
 [161] 180.50 179.52 167.16 180.20 179.90 179.43 182.12 183.84 180.00 169.42
 [171] 181.83 180.34 180.90 184.68 182.29 180.20 180.64 185.16 181.48 184.24
 [181] 181.75 183.50 184.30 183.00 181.85 187.09 181.90 181.85 179.88 185.13
 [191] 184.09 169.31 182.00 179.50 179.61 181.19 182.53 182.75 181.74 180.30
 [201] 182.18 182.20 183.59 183.35 169.09 182.32 180.54 181.69 180.62 182.30
 [211] 180.13 184.10 181.71 185.68 180.27 181.58 182.40 181.52 183.83 182.39
 [221] 185.70 171.65 184.48 182.10 180.16 166.66 182.90 185.75 182.53 171.52
 [231] 180.94 180.81 182.82 185.35 180.13 179.93 182.68 180.63 166.53 180.22
 [241] 182.74 182.84 166.00 183.68 185.51 181.67 181.65 186.90 180.01 169.50
 [251] 166.26 167.24 181.38 170.40 182.10 180.88 184.89 169.33 179.36 179.89
 [261] 184.23 181.51 169.01 181.47 183.05 184.20 167.24 168.80 182.37 180.85
 [271] 181.41 180.38 179.90 181.99 180.38 181.40 180.18 179.22 180.52 182.51
 [281] 180.10 180.54 177.77 185.00 184.68 179.85 180.60 185.32 181.57 182.28
 [291] 181.49 166.20 181.50 179.69 186.21 185.86 178.40 181.51 181.20 169.32
 [301] 169.28 184.14 185.74 181.38 171.39 179.70 181.36 180.53 181.39 181.50
 [311] 169.58 169.63 181.91 181.41 183.78 181.02 181.03 169.24 179.50 167.10
 [321] 167.32 183.48 182.04 182.31 166.36 182.30 181.20 165.77 185.77 166.24
 [331] 183.87 180.00 182.60 166.60 179.07 182.18 182.10 182.18 182.38 182.18
 [341] 182.28 181.70 182.50 182.50 182.39 182.47 182.40 182.39 185.48 182.43
 [351] 182.61 166.29 181.32 182.02 182.36 181.32 171.40 182.68 182.53 166.47
 [361] 181.58 185.72 179.60 179.90 169.21 183.61 182.37 183.20 182.51 182.93
 [371] 179.99 184.08 181.09 181.40 184.06 186.75 181.60 186.66 186.42 186.71
 [381] 167.95 167.14 182.82 167.33 182.01 181.66 181.49 180.98 165.99 183.88
 [391] 186.16 183.68 181.26 181.90 181.20 179.60 181.42 188.13 181.30 170.30
 [401] 182.16 166.14 181.40 178.59 184.50 181.50 182.30 167.51 180.23 181.60
 [411] 186.80 184.56 169.14 180.10 185.20 167.26 167.26 181.70 181.80 186.20
 [421] 180.38 182.77 186.80 179.71 180.90 182.40 181.24 182.60 169.15 180.96
 [431] 183.40 180.26 182.23 178.47 183.20 182.93 169.48 182.30 182.04 185.32
 [441] 166.37 184.68 168.52 182.54 183.81 183.52 185.64 181.59 181.50 180.15
 [451] 182.50 179.68 167.70 182.80 184.70 167.32 181.59 185.60 179.99 180.63
 [461] 186.80 180.62 180.70 180.86 181.16 181.90 167.50 185.43 181.11 180.57
 [471] 184.36 185.48 185.94 166.06 185.90 181.60 177.47 183.20 180.23 185.20
 [481] 180.68 184.87 183.30 181.21 181.30 183.40 180.50 181.20 181.13 170.62
 [491] 181.63 169.04 180.23 183.54 185.31 172.91 185.30 181.20 180.22 184.46
 [501] 187.10 186.30 183.81 166.87 180.09 182.30 165.98 165.96 165.76 180.02
 [511] 183.63 184.28 187.00 180.17 181.82 187.20 166.02 184.52 186.90 179.79
 [521] 185.77 182.54 183.33 167.38 181.15 180.84 167.18 167.01 183.13 180.80
 [531] 167.01 166.83 183.20 166.94 184.60 167.25 181.31 166.69 167.34 181.59
 [541] 167.42 166.90 166.85 166.80 166.91 167.54 166.18 181.91 187.15 181.41
 [551] 182.22 168.71 166.62 184.61 184.60 184.42 184.46 183.95 180.47 166.49
 [561] 181.57 184.47 182.10 182.80 180.97 183.91 182.26 181.18 183.84 179.82
 [571] 167.26 187.55 182.41 186.51 182.04 187.80 181.31 181.69 182.64 183.40
 [581] 167.16 181.33 166.36 181.87 181.25 186.74 168.75 179.87 181.42 179.27
 [591] 181.06 181.90 167.15 166.28 185.00 169.76 166.78 182.93 182.39 184.03
 [601] 181.96 182.25 180.81 180.86 174.46 179.80 185.50 185.62 180.92 180.20
 [611] 182.40 170.99 168.98 181.87 186.26 181.53 184.91 168.69 181.54 165.67
 [621] 181.30 179.10 179.02 180.31 171.50 179.91 181.75 179.86 172.65 182.37
 [631] 181.02 183.47 183.59 180.92 183.22 182.21 183.97 167.39 186.54 180.18
 [641] 181.09 167.91 183.40 185.01 181.41 184.00 176.03 186.73 177.52 181.38
 [651] 181.88 181.98 166.07 180.12 170.34 171.72 180.98 182.10 180.60 180.58
 [661] 180.80 182.30 180.87 180.11 181.04 180.87 180.98 184.83 180.09 184.28
 [671] 181.32 166.10 181.71 182.62 167.10 182.85 186.08 180.24 179.15 181.66
 [681] 169.37 184.27 180.94 181.74 186.40 169.10 181.24 183.32 181.54 181.50
 [691] 181.40 182.41 182.44 181.53 179.86 179.90 181.58 185.19 167.32 181.57
 [701] 167.18 177.01 181.51 180.00 184.48 187.48 179.98 186.78 183.23 181.72
 [711] 186.73 167.91 185.86 170.45 180.49 172.76 181.51 182.50 185.27 182.90
 [721] 171.40 181.48 178.30 178.29 168.08 169.71 182.80 182.78 180.00 181.69
 [731] 181.48 181.20 180.80 179.67 167.24 186.87 183.95 178.42 181.40 181.17
 [741] 181.61 186.83 185.30 175.70 183.00 181.59 181.30 183.34 180.64 180.30
 [751] 181.84 185.77 180.85 169.66 180.03 167.03 185.90 185.60 167.43 186.73
 [761] 184.30 180.92 185.33 183.86 166.75 167.41 184.52 184.51 166.55 186.30
 [771] 185.10 182.73 184.53 180.77 180.50 181.00 183.60 180.90 165.80 181.50
 [781] 171.44 171.46 184.85 186.10 184.62 183.40 166.64 180.27 185.50 181.58
 [791] 181.65 178.43 181.90 182.00 180.70 180.60 169.46 182.10 183.80 181.63
 [801] 184.70 180.21 184.80 169.52 181.06 184.97 181.30 181.75 182.02 179.84
 [811] 180.89 186.59 167.10 183.00 181.72 180.49 185.10 186.52 180.67 180.40
 [821] 179.54 186.36 179.62 182.44 168.93 182.40 166.90 185.30 185.23 183.11
 [831] 180.90 185.10 184.37 182.44 182.29 185.90 168.63 179.97 185.26 169.44
 [841] 181.62 185.25 182.65 169.90 180.05 181.23 180.26 179.98 180.48 181.39
 [851] 185.93 166.56 167.23 186.72 181.41 185.40 171.17 185.17 181.15 167.24
 [861] 180.78 180.78 181.89 181.70 166.66 169.63 181.37 185.96 174.21 167.02
 [871] 181.57 167.05 167.01 180.58 181.20 182.43 182.20 181.28 179.77 181.63
 [881] 184.84 181.40 166.20 166.30 182.69 178.98 169.50 170.04 184.52 177.10
 [891] 167.11 180.28 166.53 183.78 181.25 180.15 185.80 180.58 185.11 181.27
 [901] 180.00 185.86 180.94 181.62 181.42 181.33 179.85 170.52 169.53 182.39
 [911] 179.97 171.51 185.98 181.51 165.97 169.75 184.47 183.45 182.80 181.44
 [921] 167.95 184.41 181.61 181.77 182.22 181.02 167.32 182.72 182.54 166.01
 [931] 185.13 180.21 180.21 185.18 184.75 186.16 181.71 183.99 181.16 181.73
 [941] 181.01 182.10 182.39 183.99 184.13 182.40 182.32 182.92 184.90 184.49
 [951] 181.62 178.52 184.50 179.95 180.06 180.26 183.44 184.95 181.20 183.58
 [961] 184.60 167.44 166.72 184.23 183.95 181.59 180.13 180.74 166.98 184.64
 [971] 182.38 184.50 184.50 169.05 184.68 185.74 183.71 183.50 182.26 170.70
 [981] 181.67 170.56 183.60 183.50 187.15 166.93 171.66 170.30 181.30 184.53
 [991] 181.42 181.42 183.86 181.37 188.10 179.54 167.06 184.20 187.80 170.56</code></pre>
</div>
</div>
</section>
<section id="finding-unique-values" class="level3">
<h3 class="anchored" data-anchor-id="finding-unique-values">3 - Finding Unique Values</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(quakes<span class="sc">$</span>long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 181.62 181.03 184.10 181.66 181.96 184.31 166.10 181.93 181.74 179.59
 [11] 180.69 167.00 182.11 169.92 184.95 165.96 181.50 179.78 180.31 181.16
 [21] 166.32 180.16 182.00 180.28 181.49 167.51 180.79 181.47 182.37 179.24
 [31] 166.74 185.05 180.80 186.00 179.33 169.23 181.28 181.40 169.33 176.78
 [41] 186.10 179.82 186.04 169.41 182.30 181.70 180.08 185.25 182.35 184.42
 [51] 173.20 180.67 182.16 182.13 181.00 180.60 181.35 179.20 181.55 182.40
 [61] 172.38 166.22 181.41 184.93 181.60 179.62 181.86 187.81 185.80 184.35
 [71] 166.20 179.99 181.23 180.04 184.70 167.06 181.71 181.11 180.21 180.99
 [81] 182.38 183.40 170.50 179.96 186.30 186.44 167.53 182.02 169.71 185.26
 [91] 183.41 166.54 179.92 185.61 178.41 180.39 183.50 169.49 185.90 177.81
[101] 185.23 182.31 182.45 178.30 178.35 178.31 172.23 172.29 167.40 169.48
[111] 166.97 178.90 180.40 182.43 167.89 183.84 178.57 183.51 185.43 181.22
[121] 168.98 180.30 180.82 168.02 187.32 182.80 182.60 184.16 169.46 167.10
[131] 181.43 173.50 184.40 185.17 173.49 180.17 184.50 167.62 182.56 165.80
[141] 167.68 181.32 166.07 180.00 169.84 166.24 180.50 179.52 167.16 180.20
[151] 179.90 179.43 182.12 169.42 181.83 180.34 180.90 184.68 182.29 180.64
[161] 185.16 181.48 184.24 181.75 184.30 183.00 181.85 187.09 181.90 179.88
[171] 185.13 184.09 169.31 179.50 179.61 181.19 182.53 182.75 182.18 182.20
[181] 183.59 183.35 169.09 182.32 180.54 181.69 180.62 180.13 185.68 180.27
[191] 181.58 181.52 183.83 182.39 185.70 171.65 184.48 182.10 166.66 182.90
[201] 185.75 171.52 180.94 180.81 182.82 185.35 179.93 182.68 180.63 166.53
[211] 180.22 182.74 182.84 166.00 183.68 185.51 181.67 181.65 186.90 180.01
[221] 169.50 166.26 167.24 181.38 170.40 180.88 184.89 179.36 179.89 184.23
[231] 181.51 169.01 183.05 184.20 168.80 180.85 180.38 181.99 180.18 179.22
[241] 180.52 182.51 180.10 177.77 185.00 179.85 185.32 181.57 182.28 179.69
[251] 186.21 185.86 178.40 181.20 169.32 169.28 184.14 185.74 171.39 179.70
[261] 181.36 180.53 181.39 169.58 169.63 181.91 183.78 181.02 169.24 167.32
[271] 183.48 182.04 166.36 165.77 185.77 183.87 166.60 179.07 182.50 182.47
[281] 185.48 182.61 166.29 182.36 171.40 166.47 185.72 179.60 169.21 183.61
[291] 183.20 182.93 184.08 181.09 184.06 186.75 186.66 186.42 186.71 167.95
[301] 167.14 167.33 182.01 180.98 165.99 183.88 186.16 181.26 181.42 188.13
[311] 181.30 170.30 166.14 178.59 180.23 186.80 184.56 169.14 185.20 167.26
[321] 181.80 186.20 182.77 179.71 181.24 169.15 180.96 180.26 182.23 178.47
[331] 166.37 168.52 182.54 183.81 183.52 185.64 181.59 180.15 179.68 167.70
[341] 185.60 180.70 180.86 167.50 180.57 184.36 185.94 166.06 177.47 180.68
[351] 184.87 183.30 181.21 181.13 170.62 181.63 169.04 183.54 185.31 172.91
[361] 185.30 184.46 187.10 166.87 180.09 165.98 165.76 180.02 183.63 184.28
[371] 187.00 181.82 187.20 166.02 184.52 179.79 183.33 167.38 181.15 180.84
[381] 167.18 167.01 183.13 166.83 166.94 184.60 167.25 181.31 166.69 167.34
[391] 167.42 166.90 166.85 166.80 166.91 167.54 166.18 187.15 182.22 168.71
[401] 166.62 184.61 183.95 180.47 166.49 184.47 180.97 183.91 182.26 181.18
[411] 187.55 182.41 186.51 187.80 182.64 181.33 181.87 181.25 186.74 168.75
[421] 179.87 179.27 181.06 167.15 166.28 169.76 166.78 184.03 182.25 174.46
[431] 179.80 185.50 185.62 180.92 170.99 186.26 181.53 184.91 168.69 181.54
[441] 165.67 179.10 179.02 171.50 179.91 179.86 172.65 183.47 183.22 182.21
[451] 183.97 167.39 186.54 167.91 185.01 184.00 176.03 186.73 177.52 181.88
[461] 181.98 180.12 170.34 171.72 180.58 180.87 180.11 181.04 184.83 182.62
[471] 182.85 186.08 180.24 179.15 169.37 184.27 186.40 169.10 183.32 182.44
[481] 185.19 177.01 187.48 179.98 186.78 183.23 181.72 170.45 180.49 172.76
[491] 185.27 178.29 168.08 182.78 179.67 186.87 178.42 181.17 181.61 186.83
[501] 175.70 183.34 181.84 169.66 180.03 167.03 167.43 185.33 183.86 166.75
[511] 167.41 184.51 166.55 185.10 182.73 184.53 180.77 183.60 171.44 171.46
[521] 184.85 184.62 166.64 178.43 183.80 184.80 169.52 184.97 179.84 180.89
[531] 186.59 186.52 179.54 186.36 168.93 183.11 184.37 168.63 179.97 169.44
[541] 182.65 169.90 180.05 180.48 185.93 166.56 167.23 186.72 185.40 171.17
[551] 180.78 181.89 181.37 185.96 174.21 167.02 167.05 179.77 184.84 166.30
[561] 182.69 178.98 170.04 177.10 167.11 185.11 181.27 170.52 169.53 171.51
[571] 185.98 165.97 169.75 183.45 181.44 184.41 181.77 182.72 166.01 185.18
[581] 184.75 183.99 181.73 181.01 184.13 182.92 184.90 184.49 178.52 179.95
[591] 180.06 183.44 183.58 167.44 166.72 180.74 166.98 184.64 169.05 183.71
[601] 170.70 170.56 166.93 171.66 188.10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(quakes<span class="sc">$</span>long))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 605</code></pre>
</div>
</div>
</section>
<section id="range" class="level3">
<h3 class="anchored" data-anchor-id="range">4 - Range</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(quakes<span class="sc">$</span>depth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  40 680</code></pre>
</div>
</div>
</section>
<section id="impressing-myself" class="level3">
<h3 class="anchored" data-anchor-id="impressing-myself">Impressing Myself</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(quakes<span class="sc">$</span>mag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>quakes[quakes<span class="sc">$</span>mag <span class="sc">==</span> <span class="fl">6.4</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lat   long depth mag stations
152 -15.56 167.62   127 6.4      122</code></pre>
</div>
</div>
<p>The largest magnitude was recorded at station 122 on row 152</p>
</section>
</section>
<section id="latex-syntax" class="level1">
<h1>LaTeX Syntax</h1>
<section id="latex-mathmatical-symbols" class="level3">
<h3 class="anchored" data-anchor-id="latex-mathmatical-symbols">5 - LaTex Mathmatical Symbols</h3>
<p><span class="math display">\[
x = \mu
\]</span></p>
</section>
<section id="difference-of-equation-presenting" class="level3">
<h3 class="anchored" data-anchor-id="difference-of-equation-presenting">6 - Difference of Equation Presenting</h3>
<p>The difference between the two is, $ stays inline compared to $$ the equation is displayed <span class="math inline">\(Y_i = 3X_i\)</span> <span class="math display">\[
Y_i = 3X_i
\]</span></p>
</section>
<section id="superscripts" class="level3">
<h3 class="anchored" data-anchor-id="superscripts">7 - Superscripts</h3>
<p><span class="math display">\[
a^2 = b^2 + c^2
\]</span></p>
</section>
<section id="impress-myself" class="level3">
<h3 class="anchored" data-anchor-id="impress-myself">Impress Myself</h3>
<p><span class="math display">\[
y_i \sim \mathcal{N}(\hat{y}_i,\sigma^2)
\]</span></p>
</section>
<section id="meta-questions" class="level2">
<h2 class="anchored" data-anchor-id="meta-questions">Meta Questions</h2>
<ol type="1">
<li><p>This was not my first experience with R as I have used it slightly within a Evolution course, but throughout the introduction to R week I was slowly regain memories of how to properly use R. All though it was not the most challenging problems, I was introduced to new concepts and fleshed out the basics in order for me to gain a true comprehension of R.</p></li>
<li><p>I enjoy having the clear opportunity to learn more outside of class especially when it is more self-sufficient just like the LaTeX portion of the assignment. The LaTex portion was not too difficult, although I did struggle to find certain LaTex notations as I was looking for more specific characters. I also do see the future applicatin within LaTeX, especially when it comes to printing mathematical equations.</p></li>
<li><p>It took me roughly an hour to fully complete the assignment, as well as about an hour or so to fully set up my GitHub.</p></li>
<li><p>I would give myself a strong assessment on this assignment, as I was able to complete each portion to its fullest while fully comprehending what process were taking place.</p></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>